version: '3'
services:
  webApplication-oadin:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - meesho-network

networks:
  meesho-network:
    driver: bridge