name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t webapplication-oadin .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag webapplication-oadin ${{ secrets.DOCKER_USERNAME }}/webapplication-oadin:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/webapplication-oadin:latest

      - name: Deploy to production
        run: |
          ssh user@yourserver "docker pull ${{ secrets.DOCKER_USERNAME }}/webapplication-oadin:latest && docker-compose up -d"
